// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBmutY-neVDyjK3f-T7AYY-2ms4VDXYqU',
    appId: '1:894349650937:web:189d610a500e3bc0eceb28',
    messagingSenderId: '894349650937',
    projectId: 'myproject-d9da0',
    authDomain: 'myproject-d9da0.firebaseapp.com',
    storageBucket: 'myproject-d9da0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuxOYeCYu4e3ZCCq2bctGoTJrKCevBvQM',
    appId: '1:894349650937:android:714b1a4082beccf2eceb28',
    messagingSenderId: '894349650937',
    projectId: 'myproject-d9da0',
    storageBucket: 'myproject-d9da0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAjrXgFO5FBISpljDBDk1cMsDc2qMu-iY',
    appId: '1:894349650937:ios:13aa888b1733fbffeceb28',
    messagingSenderId: '894349650937',
    projectId: 'myproject-d9da0',
    storageBucket: 'myproject-d9da0.appspot.com',
    iosBundleId: 'com.example.project',
  );
}
